# Generated by Django 4.2.1 on 2023-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_jwt_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_request",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
